"""TTS round-trip benchmark.

  python -m bench.tts_bench            # dry: show the corpus + systems
  python -m bench.tts_bench --confirm  # synthesise + transcribe + score

Why round-trip: we have no listening panel, and the question that matters
for a voice ledger is not "does it sound nice" but "does the trader hear
the RIGHT AMOUNT". So each system speaks the app's real confirmation
lines, a neutral third-party ASR (whisper-large-v3 — never Sahara's own
ASR, which would be same-vendor circular) transcribes the audio back, and
bench/tts_metrics.py scores the round trip.

The corpus is the app's OWN readbacks, generated by tools.log_transaction
from the frozen normaliser cases — the exact sentences a trader hears.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

from sautiledger.config import get_settings
from sautiledger.ledger import Ledger
from sautiledger.models import ParseResult
from sautiledger.packs import load_pack
from sautiledger import tools

from .tts_metrics import score_roundtrip

BENCH_DIR = Path(__file__).resolve().parent
RESULTS_DIR = BENCH_DIR / "results"
TTS_RAW = RESULTS_DIR / "tts_raw"
SPEC = json.loads((BENCH_DIR.parent / "normaliser_tests.json").read_text(encoding="utf-8"))


# ------------------------------------------------------------------ corpus


def readback_corpus() -> list[dict]:
    """The app's real confirmation lines, one per frozen transaction case."""
    items: list[dict] = []
    for case in SPEC["cases"]:
        exp = case["expect"]
        if exp.get("intent") != "log_transaction":
            continue
        pack_name = case["pack"]
        parse = ParseResult(
            intent="log_transaction", type=exp.get("type"), item=exp.get("item"),
            quantity=exp.get("quantity"), unit=exp.get("unit"),
            amount=exp.get("amount"), amount_each=exp.get("amount_each"),
            currency=exp.get("currency"),
        )
        ledger = Ledger(":memory:")
        text = tools.log_transaction(ledger, parse, case["utterance"])
        items.append({
            "id": f"rb{case['id']:02d}",
            "text": text,
            "pack": pack_name,
            "expected_amount": exp.get("amount") or exp.get("amount_each"),
        })
    return items


# ------------------------------------------------------------------ systems


class SaharaTtsSystem:
    """Intron Sahara TTS. accent/language pairs are documented at
    docs.voice.intron.io/docs/tts/supported-languages-and-accents."""

    def __init__(self, language: str, accent: str, gender: str = "female"):
        from sautiledger.tts import SaharaTts

        from .bench_asr import bench_recorder

        self.name = f"sahara-tts-{accent}"
        key = os.environ.get("SAHARA_API_KEY")
        if not key:
            raise RuntimeError("SAHARA_API_KEY not set")
        self.client = SaharaTts(bench_recorder(), key, gender=gender,
                                language=language, accent=accent)

    def speak(self, text: str) -> bytes:
        return self.client.speak(text)


class PiperSystem:
    """Fully offline neural TTS — the zero-egress alternative. Needs a
    voice model; absent, the report says the comparison was unavailable."""

    def __init__(self, voice_model: str):
        from sautiledger.tts import PiperLocalTts

        self.name = "piper-local"
        self.client = PiperLocalTts(voice_model)

    def speak(self, text: str) -> bytes:
        return self.client.speak(text)


def build_systems() -> tuple[list, list[str]]:
    systems, notes = [], []
    systems.append(SaharaTtsSystem("pcm", "pidgin"))      # the deployed voice
    try:
        systems.append(SaharaTtsSystem("yo", "yoruba"))   # accent ablation
    except Exception as exc:
        notes.append(f"sahara-tts yoruba accent unavailable: {exc}")
    voice = os.environ.get("PIPER_VOICE")
    if voice and Path(voice).exists():
        try:
            systems.append(PiperSystem(voice))
        except Exception as exc:
            notes.append(f"piper-local unavailable: {exc}")
    else:
        notes.append(
            "piper-local (offline neural TTS) was not benchmarked: no Nigerian "
            "Pidgin voice model exists for Piper, and an en_US voice cannot "
            "pronounce the code-switched readback. Set PIPER_VOICE to include it."
        )
    notes.append(
        "Browser speechSynthesis (the app's fallback voice) is NOT measurable "
        "here: Chrome renders it straight to the audio device with no capture "
        "path, so no round-trip audio can be obtained. It is described "
        "qualitatively in the report instead."
    )
    return systems, notes


# ------------------------------------------------------------------ run


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--confirm", action="store_true")
    parser.add_argument("--judge", default="small", choices=["small", "large-v3"],
                        help="round-trip ASR judge. Default 'small' keeps the "
                             "memory footprint low; 'large-v3' is the stronger "
                             "judge where RAM allows.")
    parser.add_argument("--synth-only", action="store_true",
                        help="synthesise and cache audio, load no model")
    args = parser.parse_args()
    get_settings()

    corpus = readback_corpus()
    print(f"TTS corpus: {len(corpus)} real readback lines")
    for item in corpus[:3]:
        print(f"  {item['id']}: {item['text'][:70]}…")

    if not args.confirm:
        print("\nDry run. Re-run with --confirm to synthesise, transcribe and score.")
        return

    systems, notes = build_systems()
    print(f"\nSystems: {', '.join(s.name for s in systems)}")
    for note in notes:
        print(f"  note: {note}")

    # Phase 1 — synthesise everything. Network only, no model in memory.
    for system in systems:
        raw_dir = TTS_RAW / system.name
        raw_dir.mkdir(parents=True, exist_ok=True)
        for item in corpus:
            wav_path = raw_dir / f"{item['id']}.wav"
            if wav_path.exists():
                continue
            try:
                wav_path.write_bytes(system.speak(item["text"]))
                print(f"[synth] {system.name} {item['id']}", flush=True)
            except Exception as exc:
                print(f"  ! synth {system.name} {item['id']}: {exc}", flush=True)
    if args.synth_only:
        print("\nAudio cached. Re-run without --synth-only to judge and score.")
        return

    # Phase 2 — one judge, loaded once, over the cached audio.
    from .bench_asr import WhisperLocalBench

    judge = WhisperLocalBench(args.judge)
    print(f"\nround-trip judge: {judge.name} (neutral third party — never "
          f"Sahara's own ASR, which would be same-vendor circular)\n")

    results = []
    for system in systems:
        raw_dir = TTS_RAW / system.name
        for item in corpus:
            wav_path = raw_dir / f"{item['id']}.wav"
            if not wav_path.exists():
                continue
            transcript = judge.transcribe_file(wav_path, None)
            scored = score_roundtrip(item["text"], transcript,
                                     load_pack(item["pack"]), item["expected_amount"])
            results.append({"system": system.name, "id": item["id"],
                            "text": item["text"], "transcript": transcript,
                            "expected_amount": item["expected_amount"], **scored})
            print(f"[{system.name}] {item['id']} wer={scored['wer']:.2f} "
                  f"amount_survived={scored['amount_survived']}", flush=True)

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    if judge.name != "whisper-large-v3":
        notes.append(
            f"Round-trip judge was {judge.name}, not the stronger "
            "whisper-large-v3: the benchmark machine is a CPU-only laptop and the "
            "larger judge exhausted memory. A weaker judge raises the absolute "
            "error of EVERY system equally, so the comparison between TTS systems "
            "holds; the absolute numbers are an upper bound on round-trip error, "
            "not a measure of the voices alone."
        )
    (RESULTS_DIR / "tts_metrics.json").write_text(
        json.dumps({"judge": judge.name, "notes": notes, "results": results},
                   indent=2, ensure_ascii=False), encoding="utf-8")

    # summary per system
    print("\n{:<24} {:>6} {:>7} {:>8} {:>8} {:>8} {:>9}".format(
        "system", "WER", "acc", "loss", "halluc", "seg", "amount"))
    for system in systems:
        rows = [r for r in results if r["system"] == system.name]
        if not rows:
            continue
        amt = [r for r in rows if r["amount_survived"] is not None]
        print("{:<24} {:>6.3f} {:>7.2f} {:>8.3f} {:>8.3f} {:>8.3f} {:>8.0f}%".format(
            system.name,
            sum(r["wer"] for r in rows) / len(rows),
            sum(r["accuracy"] for r in rows) / len(rows),
            sum(r["transcript_loss"] for r in rows) / len(rows),
            sum(r["hallucination"] for r in rows) / len(rows),
            sum(r["segment_loss"] for r in rows) / len(rows),
            100 * sum(bool(r["amount_survived"]) for r in amt) / max(len(amt), 1),
        ))
    print(f"\nWrote {RESULTS_DIR / 'tts_metrics.json'}")


if __name__ == "__main__":
    main()
